const text = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum turpis diam, aliquet at elit vel, facilisis efficitur nibh. Nam ultricies dignissim purus, et ultricies velit faucibus at. Maecenas diam dui, dapibus nec augue dapibus, pellentesque vestibulum tellus. In tempor mi metus, ac placerat nisi facilisis et. Mauris feugiat felis vel lorem condimentum, a ornare tortor ultricies. Mauris ipsum felis, feugiat non justo quis, congue ultricies dui. Mauris sagittis urna ut ligula pulvinar, luctus vestibulum arcu maximus. Duis dignissim auctor dolor eget pharetra.",

  "Nulla ante orci, ultricies ac aliquam quis, tempus nec arcu. Cras id nulla sollicitudin, finibus massa elementum, eleifend mauris. Ut efficitur quam a bibendum accumsan. Integer felis quam, pulvinar nec enim a, varius pellentesque lacus. Donec tellus lorem, tristique sed nunc a, malesuada pellentesque ipsum. Vivamus et lobortis ipsum, vitae consequat mi. Maecenas lobortis hendrerit risus, facilisis elementum nisi dignissim eget. Cras lacinia metus ac dui vulputate, quis dapibus turpis ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam lobortis a purus a malesuada.",

  "Phasellus dictum massa sed neque elementum, nec fermentum ante egestas. Nullam interdum magna sit amet rutrum vulputate. Aliquam id tellus ut mi porttitor sollicitudin. Donec vestibulum elit id ligula tincidunt, nec imperdiet justo iaculis. Nullam lobortis nibh sit amet quam elementum malesuada non in orci. Nam elementum dolor ut odio bibendum, nec commodo lectus tempus. Aliquam erat volutpat. Aenean nec lectus elit. Quisque luctus risus felis, vitae efficitur libero consequat eget. Proin cursus erat vel elit commodo vestibulum. Morbi nec feugiat nisl, non tempus lacus. Proin at lorem ut orci suscipit porttitor. Fusce finibus, orci sed vulputate fringilla, quam ante facilisis nulla, vel pulvinar lacus urna quis mi. Donec sed orci egestas, euismod nisl eget, tincidunt sem. Aenean sed eros eget est maximus ultrices in vitae massa.",

  "Sed vitae varius tortor. Suspendisse sodales sapien iaculis, aliquet tortor non, malesuada mauris. Pellentesque non mi non magna euismod hendrerit. Pellentesque ac felis tellus. Nam sit amet interdum ex. Quisque eros quam, accumsan vitae felis sed, sodales pellentesque metus. Praesent felis elit, fermentum ac mauris lobortis, rutrum tristique velit. Curabitur euismod semper ligula vel convallis. Praesent sollicitudin ipsum velit, vitae imperdiet quam vestibulum at. Cras felis massa, venenatis non erat nec, imperdiet commodo velit. Sed maximus, sapien eu maximus sollicitudin, leo massa aliquet tellus, in bibendum mauris eros sit amet ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",

  "Suspendisse quam orci, accumsan id congue viverra, pretium a dui. Aliquam in erat arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed vitae accumsan velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam id neque in tortor convallis venenatis. Donec blandit arcu et ipsum faucibus, sit amet aliquam magna consectetur. Etiam molestie, sem ac imperdiet finibus, neque arcu vulputate arcu, a laoreet metus arcu ut lectus. Nam ornare, mi id fringilla iaculis, leo tellus interdum ligula, eu pulvinar risus ex et metus. Aenean fringilla ante sed venenatis tincidunt."
];

export default text;
